### ISSUE TITLE
폴더 추가를 요청합니다.

### ISSUE THREAD

**Issue by hotbreakb** [Egg-Ring/Cooking#31]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/64337152/163701054-f4b107e2-0f60-405d-b2db-70b30e7673a5.png">

문제를 풀면서 파일을 찾는 것이 더욱 어려워졌습니다. `command + p`로 열어도 되지만 저는 마우스로 클릭해서 여는 것이 조금 더 편합니다😉

**Comment by WhiteHyun** [comment]
어떻게 폴더링하면 좋을까용?

**Comment by hotbreakb** [comment]
level 단위로 나누는 게 제일 무난하지 않을까요?

**Comment by WhiteHyun** [comment]
그러면 `pgs.zsh` 스크립트를 사용하고난 뒤,파일을 레벨 폴더로 이동해야하는 번거로움이 있는데 괜찮나요?

**Comment by hotbreakb** [comment]
굳이 그러지 않아도 `$ ./pgs.zsh 문제번호 닉네임/level2` 이렇게 하면 돼서 괜찮을 거 같아요!

**Comment by WhiteHyun** [comment]
알겠습니다! README 수정해서 올릴게요~
